// Medical Records Components
export { CheckboxGroup } from './checkbox-group'
export { SectionPatientData } from './section-patient-data'
export { SectionSymptoms } from './section-symptoms'
export { SectionOnset } from './section-onset'
export { SectionHistory } from './section-history'
export { SectionDiagnosis } from './section-diagnosis'
export { SectionCeap } from './section-ceap'
export { SectionVascularLab } from './section-vascular-lab'
export { SectionTreatment } from './section-treatment'
export { SectionDiagram } from './section-diagram'
export { VeinDiagramCanvas } from './vein-diagram-canvas'
export { VoiceDictation } from './voice-dictation'
export { VoiceRecorder } from './voice-recorder'
export { TreatmentSelector, BODY_ZONES, type TreatmentItem, type BodyZone } from './treatment-selector'
export { RecordTabs } from './record-tabs'
export { MedicalRecordForm } from './medical-record-form'
export { QuotationPanel } from './quotation-panel'
export { ProgressNotes } from './progress-notes'
export { MedicalRecordSearch } from './medical-record-search'
export { LegacyPhotoCapture } from './legacy-photo-capture'
export { LegacyPhotosGallery } from './legacy-photos-gallery'
export { AppointmentPicker } from './appointment-picker'
export { MarkAttendedButton } from './mark-attended-button'
