-- Migration: 021_medias_sales.sql
-- Purpose: Sales tables for medias de compresion with gapless VTA- numbering
-- Phase: 11-sales-core, Plan: 01
-- Created: 2026-01-26
-- Depends on: 009_payments_tables.sql (ENUM types), 020_medias_foundation.sql (medias_products)
--
-- Requirements covered by this migration:
--   VTA-05: Electronic payments require comprobante photo
--   VTA-06: Optional patient link
--   VTA-07: vendedor_id tracks who made the sale
--   VTA-08: receptor_efectivo_id for cash handler when different from seller
--   VTA-10: Gapless sequential numbering (VTA-000001)
--
-- NOTE: This follows 009_payments_tables.sql pattern exactly
-- Immutability and delete with stock reversal are handled in 022_medias_sales_immutability.sql

-- ============================================================================
-- 1. VENTA COUNTER TABLE (GAPLESS NUMBERING)
-- ============================================================================
-- VTA-10: Numeros de venta son secuenciales automaticos y nunca se reutilizan
-- Single-row table for gapless sequential venta numbers
-- PostgreSQL sequences have gaps on rollback; this counter ensures gapless numbering

CREATE TABLE public.venta_counter (
  id INTEGER PRIMARY KEY DEFAULT 1,
  last_number BIGINT NOT NULL DEFAULT 0,
  prefix VARCHAR(10) NOT NULL DEFAULT 'VTA',

  -- Single-row enforcement: only id=1 allowed
  CONSTRAINT venta_counter_single_row CHECK (id = 1)
);

COMMENT ON TABLE public.venta_counter IS 'Contador de ventas con numeracion secuencial sin gaps - solo una fila permitida (VTA-10)';
COMMENT ON COLUMN public.venta_counter.last_number IS 'Ultimo numero de venta generado';
COMMENT ON COLUMN public.venta_counter.prefix IS 'Prefijo para el numero de venta (VTA)';

-- Initialize counter with single row
INSERT INTO public.venta_counter (id, last_number, prefix) VALUES (1, 0, 'VTA');

-- ============================================================================
-- 2. VENTA COUNTER PROTECTION TRIGGER
-- ============================================================================

-- Prevent DELETE and multiple INSERTs on venta_counter
CREATE OR REPLACE FUNCTION public.protect_venta_counter()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'No se puede eliminar el contador de ventas';
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF (SELECT COUNT(*) FROM public.venta_counter) > 0 THEN
      RAISE EXCEPTION 'Solo puede existir un contador de ventas';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER tr_protect_venta_counter
  BEFORE INSERT OR DELETE ON public.venta_counter
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_venta_counter();

-- ============================================================================
-- 3. GET NEXT VENTA NUMBER FUNCTION
-- ============================================================================

-- Atomically get next venta number with exclusive row lock
-- CRITICAL: Called within transaction, uses FOR UPDATE to prevent race conditions
-- VTA-10: Ensures gapless sequential numbering
CREATE OR REPLACE FUNCTION public.get_next_venta_number()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  next_num BIGINT;
  prefix_val VARCHAR(10);
BEGIN
  -- Lock the counter row exclusively (FOR UPDATE)
  -- This prevents concurrent transactions from getting the same number
  SELECT last_number + 1, prefix
  INTO next_num, prefix_val
  FROM public.venta_counter
  WHERE id = 1
  FOR UPDATE;

  -- Update the counter atomically
  UPDATE public.venta_counter
  SET last_number = next_num
  WHERE id = 1;

  -- Return formatted venta number: VTA-000001
  RETURN prefix_val || '-' || LPAD(next_num::text, 6, '0');
END;
$$;

COMMENT ON FUNCTION public.get_next_venta_number() IS 'Genera el siguiente numero de venta con bloqueo exclusivo para evitar gaps (VTA-10)';

-- ============================================================================
-- 4. MEDIAS_SALES TABLE (HEADER)
-- ============================================================================

CREATE TABLE public.medias_sales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Venta number (generated by get_next_venta_number())
  -- VTA-10: Sequential, never reused
  numero_venta VARCHAR(20) NOT NULL UNIQUE,

  -- VTA-06: Optional patient link (can sell to non-patient customers)
  patient_id UUID REFERENCES public.patients(id) ON DELETE RESTRICT,

  -- Totals
  subtotal DECIMAL(12,2) NOT NULL,
  total DECIMAL(12,2) NOT NULL,

  -- Status (reuse payment_status ENUM from 009)
  -- Only 'activo' -> 'anulado' allowed, enforced by trigger in 022
  estado public.payment_status NOT NULL DEFAULT 'activo',

  -- VTA-09: Admin delete fields (populated when admin deletes)
  eliminado_por UUID REFERENCES auth.users(id),
  eliminado_at TIMESTAMPTZ,
  eliminacion_justificacion TEXT,

  -- VTA-07: Who made the sale (logged automatically)
  vendedor_id UUID NOT NULL REFERENCES auth.users(id),

  -- VTA-08: Who received the cash (if different from seller)
  receptor_efectivo_id UUID REFERENCES auth.users(id),

  -- Audit (NO updated_at - sales are immutable)
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- ============================================================================
  -- CONSTRAINTS
  -- ============================================================================

  -- Total must be non-negative
  CONSTRAINT medias_sales_total_positive CHECK (total >= 0),
  CONSTRAINT medias_sales_subtotal_positive CHECK (subtotal >= 0)
);

-- Table comments
COMMENT ON TABLE public.medias_sales IS 'Ventas inmutables de medias de compresion - solo Admin puede eliminar con justificacion (VTA-09)';
COMMENT ON COLUMN public.medias_sales.numero_venta IS 'Numero de venta secuencial sin gaps VTA-000001 (VTA-10)';
COMMENT ON COLUMN public.medias_sales.patient_id IS 'Paciente opcional - permite ventas a clientes externos (VTA-06)';
COMMENT ON COLUMN public.medias_sales.estado IS 'Solo transicion activo -> anulado permitida (VTA-09)';
COMMENT ON COLUMN public.medias_sales.eliminado_por IS 'Admin que elimino la venta (VTA-09)';
COMMENT ON COLUMN public.medias_sales.eliminacion_justificacion IS 'Obligatorio al eliminar - explica razon (VTA-09)';
COMMENT ON COLUMN public.medias_sales.vendedor_id IS 'Quien registro la venta (VTA-07)';
COMMENT ON COLUMN public.medias_sales.receptor_efectivo_id IS 'Quien recibio el efectivo si diferente al vendedor (VTA-08)';

-- ============================================================================
-- 5. MEDIAS_SALE_ITEMS TABLE (LINE ITEMS WITH SNAPSHOTS)
-- ============================================================================

CREATE TABLE public.medias_sale_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Sale reference (RESTRICT delete to protect data integrity)
  sale_id UUID NOT NULL REFERENCES public.medias_sales(id) ON DELETE RESTRICT,

  -- Product reference (keeps link for analytics)
  product_id UUID NOT NULL REFERENCES public.medias_products(id) ON DELETE RESTRICT,

  -- Snapshot of product at time of sale (IMMUTABLE - even if product changes later)
  -- VTA-03: Prices captured at sale time for accurate totals
  product_codigo VARCHAR(20) NOT NULL,
  product_tipo VARCHAR(20) NOT NULL,
  product_talla VARCHAR(10) NOT NULL,
  unit_price DECIMAL(12,2) NOT NULL,

  -- Quantity and calculated subtotal
  -- VTA-02: Quantity per product
  quantity INTEGER NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL,

  -- Audit
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- ============================================================================
  -- CONSTRAINTS
  -- ============================================================================

  CONSTRAINT medias_sale_items_quantity_positive CHECK (quantity > 0),
  CONSTRAINT medias_sale_items_unit_price_positive CHECK (unit_price >= 0)
);

-- Table comments
COMMENT ON TABLE public.medias_sale_items IS 'Items de venta con snapshot del producto al momento de la venta';
COMMENT ON COLUMN public.medias_sale_items.product_codigo IS 'Codigo del producto al momento de la venta (snapshot inmutable)';
COMMENT ON COLUMN public.medias_sale_items.product_tipo IS 'Tipo del producto al momento de la venta (snapshot inmutable)';
COMMENT ON COLUMN public.medias_sale_items.product_talla IS 'Talla del producto al momento de la venta (snapshot inmutable)';
COMMENT ON COLUMN public.medias_sale_items.unit_price IS 'Precio unitario al momento de la venta (snapshot inmutable)';
COMMENT ON COLUMN public.medias_sale_items.quantity IS 'Cantidad vendida (VTA-02)';

-- ============================================================================
-- 6. MEDIAS_SALE_METHODS TABLE (PAYMENT METHODS)
-- ============================================================================

CREATE TABLE public.medias_sale_methods (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Sale reference (RESTRICT delete to protect data integrity)
  sale_id UUID NOT NULL REFERENCES public.medias_sales(id) ON DELETE RESTRICT,

  -- VTA-04: Method and amount (reuse payment_method_type ENUM from 009)
  metodo public.payment_method_type NOT NULL,
  monto DECIMAL(12,2) NOT NULL,

  -- Receipt photo path (Supabase Storage)
  -- VTA-05: Required for electronic payments (tarjeta, transferencia, nequi)
  comprobante_path TEXT,

  -- Audit
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- ============================================================================
  -- CONSTRAINTS
  -- ============================================================================

  -- Amount must be positive
  CONSTRAINT medias_sale_methods_monto_positive CHECK (monto > 0),

  -- VTA-05: Electronic payments require receipt photo (anti-fraud)
  CONSTRAINT comprobante_required_for_electronic CHECK (
    metodo = 'efectivo' OR comprobante_path IS NOT NULL
  )
);

-- Table comments
COMMENT ON TABLE public.medias_sale_methods IS 'Metodos de pago usados en venta - soporta pagos divididos (VTA-04)';
COMMENT ON COLUMN public.medias_sale_methods.comprobante_path IS 'Ruta en Supabase Storage - OBLIGATORIO para pagos electronicos (VTA-05)';
COMMENT ON CONSTRAINT comprobante_required_for_electronic ON public.medias_sale_methods IS 'Pagos electronicos requieren foto de comprobante obligatoria (VTA-05)';

-- ============================================================================
-- 7. INDEXES
-- ============================================================================

-- Medias sales indexes
CREATE INDEX idx_medias_sales_patient ON public.medias_sales(patient_id) WHERE patient_id IS NOT NULL;
CREATE INDEX idx_medias_sales_estado ON public.medias_sales(estado);
CREATE INDEX idx_medias_sales_created_at ON public.medias_sales(created_at DESC);
CREATE INDEX idx_medias_sales_vendedor ON public.medias_sales(vendedor_id);

-- Sale items indexes
CREATE INDEX idx_medias_sale_items_sale ON public.medias_sale_items(sale_id);
CREATE INDEX idx_medias_sale_items_product ON public.medias_sale_items(product_id);

-- Sale methods indexes
CREATE INDEX idx_medias_sale_methods_sale ON public.medias_sale_methods(sale_id);

-- ============================================================================
-- 8. ROW LEVEL SECURITY
-- ============================================================================

-- MEDIAS_SALES TABLE RLS
ALTER TABLE public.medias_sales ENABLE ROW LEVEL SECURITY;

-- All staff can view sales
CREATE POLICY "Staff can view medias sales"
  ON public.medias_sales FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'medico', 'enfermera', 'secretaria')
    )
  );

-- All staff can create sales
CREATE POLICY "Staff can create medias sales"
  ON public.medias_sales FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'medico', 'enfermera', 'secretaria')
    )
  );

-- NO UPDATE policy at RLS level (trigger in 022 will handle admin delete)
-- NO DELETE policy (sales cannot be deleted directly, only marked as anulado)

-- MEDIAS_SALE_ITEMS TABLE RLS
ALTER TABLE public.medias_sale_items ENABLE ROW LEVEL SECURITY;

-- All staff can view sale items
CREATE POLICY "Staff can view medias sale items"
  ON public.medias_sale_items FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'medico', 'enfermera', 'secretaria')
    )
  );

-- All staff can create sale items
CREATE POLICY "Staff can create medias sale items"
  ON public.medias_sale_items FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'medico', 'enfermera', 'secretaria')
    )
  );

-- NO UPDATE policy (sale items are immutable)
-- NO DELETE policy (sale items cannot be deleted)

-- MEDIAS_SALE_METHODS TABLE RLS
ALTER TABLE public.medias_sale_methods ENABLE ROW LEVEL SECURITY;

-- All staff can view sale methods
CREATE POLICY "Staff can view medias sale methods"
  ON public.medias_sale_methods FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'medico', 'enfermera', 'secretaria')
    )
  );

-- All staff can create sale methods
CREATE POLICY "Staff can create medias sale methods"
  ON public.medias_sale_methods FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'medico', 'enfermera', 'secretaria')
    )
  );

-- NO UPDATE policy (sale methods are immutable)
-- NO DELETE policy (sale methods cannot be deleted)

-- VENTA_COUNTER TABLE RLS (admin only)
ALTER TABLE public.venta_counter ENABLE ROW LEVEL SECURITY;

-- Only service role and admin can view counter
CREATE POLICY "Admin can view venta counter"
  ON public.venta_counter FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role = 'admin'
    )
  );

-- Allow UPDATE for venta number generation (via function)
CREATE POLICY "Allow venta counter update"
  ON public.venta_counter FOR UPDATE
  TO authenticated
  WITH CHECK (true);

-- ============================================================================
-- 9. GRANT PERMISSIONS
-- ============================================================================

GRANT SELECT, INSERT ON public.medias_sales TO authenticated;
GRANT SELECT, INSERT ON public.medias_sale_items TO authenticated;
GRANT SELECT, INSERT ON public.medias_sale_methods TO authenticated;
GRANT SELECT, UPDATE ON public.venta_counter TO authenticated;

-- ============================================================================
-- 10. VERIFICATION
-- ============================================================================

-- Verify RLS is enabled on all tables
DO $$
BEGIN
  -- Check medias_sales
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'medias_sales' AND rowsecurity = true
  ) THEN
    RAISE EXCEPTION 'RLS not enabled on medias_sales table';
  END IF;

  -- Check medias_sale_items
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'medias_sale_items' AND rowsecurity = true
  ) THEN
    RAISE EXCEPTION 'RLS not enabled on medias_sale_items table';
  END IF;

  -- Check medias_sale_methods
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'medias_sale_methods' AND rowsecurity = true
  ) THEN
    RAISE EXCEPTION 'RLS not enabled on medias_sale_methods table';
  END IF;

  -- Check venta_counter
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'venta_counter' AND rowsecurity = true
  ) THEN
    RAISE EXCEPTION 'RLS not enabled on venta_counter table';
  END IF;
END;
$$;

-- Verify venta counter has exactly one row
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.venta_counter) != 1 THEN
    RAISE EXCEPTION 'Venta counter must have exactly one row';
  END IF;

  -- Verify counter is initialized correctly
  IF NOT EXISTS (
    SELECT 1 FROM public.venta_counter
    WHERE id = 1 AND last_number = 0 AND prefix = 'VTA'
  ) THEN
    RAISE EXCEPTION 'Venta counter not initialized correctly';
  END IF;
END;
$$;

-- Verify comprobante constraint exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'comprobante_required_for_electronic'
    AND table_name = 'medias_sale_methods'
  ) THEN
    RAISE EXCEPTION 'comprobante_required_for_electronic constraint missing on medias_sale_methods';
  END IF;
END;
$$;

-- ============================================================================
-- Summary of VTA requirements addressed:
-- VTA-04: Payment methods via medias_sale_methods table
-- VTA-05: comprobante_required_for_electronic constraint
-- VTA-06: patient_id NULLABLE on medias_sales
-- VTA-07: vendedor_id NOT NULL on medias_sales
-- VTA-08: receptor_efectivo_id NULLABLE on medias_sales
-- VTA-09: eliminado_* fields ready for admin delete (trigger in 022)
-- VTA-10: venta_counter + get_next_venta_number() for gapless numbering
--
-- Pending for 022_medias_sales_immutability.sql:
-- VTA-09: Immutability trigger, admin-only delete with justification
-- VTA-11: Stock decrement on sale (RPC in 023)
-- VTA-12: Stock validation (RPC in 023)
-- VTA-13: Stock reversal on delete (RPC in 022/023)
-- ============================================================================
