-- Migration: 024_medias_cierres.sql
-- Purpose: Cash closing (Cierre de Caja) for medias de compresion - independent from clinic
-- Phase: 12-cash-closing-medias, Plan: 01
-- Created: 2026-01-26
-- Depends on: 015_cash_closings.sql (cierre_estado ENUM), 021_medias_sales.sql (medias_sales table)
--
-- Requirements covered by this migration:
--   CIE-01: Cierre diario (one closing per day)
--   CIE-02: Totales separados por metodo (efectivo, tarjeta, transferencia, nequi)
--   CIE-03: Conteo fisico de efectivo con diferencia calculada
--   CIE-04: ZERO TOLERANCE - any difference requires justification (no threshold)
--   CIE-05: Sales lockdown - no medias_sales on closed days
--   CIE-06: Photo evidence required
--   CIE-07: Admin reopen with justification
--   CIE-08: Independent from clinic (CIM- prefix, not CIE-)
--
-- NOTE: Uses cierre_estado ENUM from 015_cash_closings.sql
-- Lockdown blocks medias_sales (NOT payments) per CIE-08 independence

-- ============================================================================
-- 1. MEDIAS CIERRE COUNTER TABLE (GAPLESS NUMBERING)
-- ============================================================================
-- CIE-08: Independent numbering with CIM prefix (not CIE)
-- Single-row table for gapless sequential closing numbers

CREATE TABLE public.medias_cierre_counter (
  id INTEGER PRIMARY KEY DEFAULT 1,
  last_number BIGINT NOT NULL DEFAULT 0,
  prefix VARCHAR(10) NOT NULL DEFAULT 'CIM',

  -- Single-row enforcement: only id=1 allowed
  CONSTRAINT medias_cierre_single_row CHECK (id = 1)
);

COMMENT ON TABLE public.medias_cierre_counter IS 'Contador de cierres medias con numeracion secuencial sin gaps - solo una fila permitida (CIM-XXXXXX)';
COMMENT ON COLUMN public.medias_cierre_counter.last_number IS 'Ultimo numero de cierre medias generado';
COMMENT ON COLUMN public.medias_cierre_counter.prefix IS 'Prefijo para el numero de cierre medias (CIM = Cierre Inventario Medias)';

-- Initialize counter with single row
INSERT INTO public.medias_cierre_counter (id, last_number, prefix) VALUES (1, 0, 'CIM');

-- ============================================================================
-- 2. MEDIAS CIERRE COUNTER PROTECTION TRIGGER
-- ============================================================================

-- Prevent DELETE and multiple INSERTs on medias_cierre_counter
CREATE OR REPLACE FUNCTION public.protect_medias_cierre_counter()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'No se puede eliminar el contador de cierres medias';
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF (SELECT COUNT(*) FROM public.medias_cierre_counter) > 0 THEN
      RAISE EXCEPTION 'Solo puede existir un contador de cierres medias';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER tr_protect_medias_cierre_counter
  BEFORE INSERT OR DELETE ON public.medias_cierre_counter
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_medias_cierre_counter();

-- ============================================================================
-- 3. GET NEXT MEDIAS CIERRE NUMBER FUNCTION
-- ============================================================================

-- Atomically get next medias cierre number with exclusive row lock
-- CRITICAL: Called within transaction, uses FOR UPDATE to prevent race conditions
CREATE OR REPLACE FUNCTION public.get_next_medias_cierre_number()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  next_num BIGINT;
  prefix_val VARCHAR(10);
BEGIN
  -- Lock the counter row exclusively (FOR UPDATE)
  -- This prevents concurrent transactions from getting the same number
  SELECT last_number + 1, prefix
  INTO next_num, prefix_val
  FROM public.medias_cierre_counter
  WHERE id = 1
  FOR UPDATE;

  -- Update the counter atomically
  UPDATE public.medias_cierre_counter
  SET last_number = next_num
  WHERE id = 1;

  -- Return formatted cierre number: CIM-000001
  RETURN prefix_val || '-' || LPAD(next_num::text, 6, '0');
END;
$$;

COMMENT ON FUNCTION public.get_next_medias_cierre_number() IS 'Genera el siguiente numero de cierre medias con bloqueo exclusivo para evitar gaps (CIM-XXXXXX)';

-- ============================================================================
-- 4. MEDIAS_CIERRES TABLE
-- ============================================================================

CREATE TABLE public.medias_cierres (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Sequential closing number (generated by get_next_medias_cierre_number())
  -- CIE-08: Uses CIM prefix for independence
  cierre_numero VARCHAR(20) NOT NULL UNIQUE,

  -- CIE-01: One closing per day
  fecha_cierre DATE NOT NULL UNIQUE,

  -- CIE-02: Calculated totals from medias_sales (snapshot at closing time)
  total_efectivo DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_tarjeta DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_transferencia DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_nequi DECIMAL(12,2) NOT NULL DEFAULT 0,
  grand_total DECIMAL(12,2) NOT NULL DEFAULT 0,

  -- CIE-03: Physical cash count entered by staff
  conteo_fisico_efectivo DECIMAL(12,2) NOT NULL,

  -- CIE-03: Difference (conteo - total_efectivo), calculated
  diferencia DECIMAL(12,2) NOT NULL DEFAULT 0,

  -- CIE-04: MANDATORY if diferencia != 0 (ZERO TOLERANCE policy)
  diferencia_justificacion TEXT,

  -- CIE-06: Photo of signed printed report (mandatory)
  cierre_photo_path TEXT NOT NULL,

  -- Status (reuse cierre_estado ENUM from 015)
  estado public.cierre_estado NOT NULL DEFAULT 'cerrado',

  -- Optional notes
  notas TEXT,

  -- Who closed
  closed_by UUID NOT NULL REFERENCES auth.users(id),

  -- CIE-07: Reopen tracking (only admin can reopen)
  reopened_by UUID REFERENCES auth.users(id),
  reopened_at TIMESTAMPTZ,
  reopen_justificacion TEXT,

  -- Audit timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- ============================================================================
  -- CONSTRAINTS
  -- ============================================================================

  -- All totals must be non-negative
  CONSTRAINT medias_cierre_totals_positive CHECK (
    total_efectivo >= 0 AND total_tarjeta >= 0 AND
    total_transferencia >= 0 AND total_nequi >= 0 AND
    grand_total >= 0 AND conteo_fisico_efectivo >= 0
  ),

  -- CIE-04: ZERO TOLERANCE - ANY difference requires justification
  -- (differs from clinic's $10k threshold - medias has no threshold)
  CONSTRAINT medias_diferencia_requires_justificacion CHECK (
    diferencia = 0 OR
    (diferencia_justificacion IS NOT NULL AND LENGTH(TRIM(diferencia_justificacion)) >= 10)
  ),

  -- CIE-07: Reopen must have justification
  CONSTRAINT medias_reopen_requires_justificacion CHECK (
    reopened_by IS NULL OR
    (reopen_justificacion IS NOT NULL AND LENGTH(TRIM(reopen_justificacion)) >= 10)
  )
);

-- Table comments
COMMENT ON TABLE public.medias_cierres IS 'Cierres de caja medias - un cierre por dia, bloquea ventas post-cierre (CIE-08: independiente de clinica)';
COMMENT ON COLUMN public.medias_cierres.cierre_numero IS 'Numero de cierre secuencial sin gaps (CIM-000001)';
COMMENT ON COLUMN public.medias_cierres.fecha_cierre IS 'Fecha que cubre este cierre (UNIQUE - un cierre por dia)';
COMMENT ON COLUMN public.medias_cierres.conteo_fisico_efectivo IS 'Conteo fisico del efectivo ingresado por staff';
COMMENT ON COLUMN public.medias_cierres.diferencia IS 'Diferencia entre conteo fisico y total efectivo calculado';
COMMENT ON COLUMN public.medias_cierres.diferencia_justificacion IS 'Obligatorio si diferencia != 0 (TOLERANCIA CERO - CIE-04)';
COMMENT ON COLUMN public.medias_cierres.cierre_photo_path IS 'Ruta en Storage de la foto del reporte impreso firmado (CIE-06)';
COMMENT ON COLUMN public.medias_cierres.estado IS 'cerrado = normal, reabierto = admin lo reabrio con justificacion';

-- ============================================================================
-- 5. INDEXES
-- ============================================================================

CREATE INDEX idx_medias_cierres_fecha ON public.medias_cierres(fecha_cierre DESC);
CREATE INDEX idx_medias_cierres_estado ON public.medias_cierres(estado);
CREATE INDEX idx_medias_cierres_created_at ON public.medias_cierres(created_at DESC);

-- ============================================================================
-- 6. IMMUTABILITY TRIGGER FOR MEDIAS_CIERRES
-- ============================================================================

-- Only allows estado transitions:
-- 'cerrado' -> 'reabierto' (with justification)
-- 'reabierto' -> 'cerrado' (re-closing)
CREATE OR REPLACE FUNCTION public.enforce_medias_cierre_immutability()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  -- Cannot delete medias cierres
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'No se pueden eliminar cierres de caja medias';
  END IF;

  -- UPDATE restrictions
  IF TG_OP = 'UPDATE' THEN
    -- Core fields are immutable
    IF OLD.cierre_numero IS DISTINCT FROM NEW.cierre_numero THEN
      RAISE EXCEPTION 'No se puede modificar el numero de cierre';
    END IF;

    IF OLD.fecha_cierre IS DISTINCT FROM NEW.fecha_cierre THEN
      RAISE EXCEPTION 'No se puede modificar la fecha de cierre';
    END IF;

    IF OLD.closed_by IS DISTINCT FROM NEW.closed_by THEN
      RAISE EXCEPTION 'No se puede modificar quien cerro';
    END IF;

    IF OLD.created_at IS DISTINCT FROM NEW.created_at THEN
      RAISE EXCEPTION 'No se puede modificar la fecha de creacion';
    END IF;

    -- Totals are immutable
    IF OLD.total_efectivo IS DISTINCT FROM NEW.total_efectivo
       OR OLD.total_tarjeta IS DISTINCT FROM NEW.total_tarjeta
       OR OLD.total_transferencia IS DISTINCT FROM NEW.total_transferencia
       OR OLD.total_nequi IS DISTINCT FROM NEW.total_nequi
       OR OLD.grand_total IS DISTINCT FROM NEW.grand_total THEN
      RAISE EXCEPTION 'No se pueden modificar los totales del cierre';
    END IF;

    IF OLD.conteo_fisico_efectivo IS DISTINCT FROM NEW.conteo_fisico_efectivo THEN
      RAISE EXCEPTION 'No se puede modificar el conteo fisico';
    END IF;

    IF OLD.diferencia IS DISTINCT FROM NEW.diferencia THEN
      RAISE EXCEPTION 'No se puede modificar la diferencia';
    END IF;

    IF OLD.diferencia_justificacion IS DISTINCT FROM NEW.diferencia_justificacion THEN
      RAISE EXCEPTION 'No se puede modificar la justificacion de diferencia';
    END IF;

    IF OLD.cierre_photo_path IS DISTINCT FROM NEW.cierre_photo_path THEN
      RAISE EXCEPTION 'No se puede modificar la foto del cierre';
    END IF;

    -- Estado transitions
    IF OLD.estado IS DISTINCT FROM NEW.estado THEN
      -- Only allowed transitions
      IF OLD.estado = 'cerrado' AND NEW.estado = 'reabierto' THEN
        -- Valid: reopen requires justification (checked by constraint)
        IF NEW.reopened_by IS NULL THEN
          RAISE EXCEPTION 'Se requiere registrar quien reabre el cierre';
        END IF;
        NEW.reopened_at := now();
      ELSIF OLD.estado = 'reabierto' AND NEW.estado = 'cerrado' THEN
        -- Valid: re-closing (just update estado)
        NULL;
      ELSE
        RAISE EXCEPTION 'Transicion de estado no permitida: % -> %', OLD.estado, NEW.estado;
      END IF;
    END IF;

    NEW.updated_at := now();
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER tr_medias_cierre_immutability
  BEFORE UPDATE OR DELETE ON public.medias_cierres
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_medias_cierre_immutability();

-- ============================================================================
-- 7. BLOCK MEDIAS SALES ON CLOSED DAYS TRIGGER
-- ============================================================================

-- CIE-05: CRITICAL - Prevents creating medias_sales on days that have been closed
-- CIE-08: Blocks medias_sales (NOT payments) for independence from clinic
CREATE OR REPLACE FUNCTION public.block_medias_sales_on_closed_day()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_sale_date DATE;
  v_closing_exists BOOLEAN;
BEGIN
  -- Get the date of the sale (using created_at)
  v_sale_date := DATE(NEW.created_at);

  -- Check if there's a closed cierre for this date
  SELECT EXISTS (
    SELECT 1 FROM public.medias_cierres
    WHERE fecha_cierre = v_sale_date
    AND estado = 'cerrado'
  ) INTO v_closing_exists;

  IF v_closing_exists THEN
    RAISE EXCEPTION 'No se pueden crear ventas en un dia cerrado (%). El cierre debe reabrirse primero.', v_sale_date;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER tr_block_medias_sales_on_closed_day
  BEFORE INSERT ON public.medias_sales
  FOR EACH ROW
  EXECUTE FUNCTION public.block_medias_sales_on_closed_day();

COMMENT ON FUNCTION public.block_medias_sales_on_closed_day() IS 'Bloquea la creacion de ventas medias en dias que ya fueron cerrados (CIE-05)';

-- ============================================================================
-- 8. ROW LEVEL SECURITY
-- ============================================================================

-- MEDIAS_CIERRES TABLE RLS
ALTER TABLE public.medias_cierres ENABLE ROW LEVEL SECURITY;

-- All staff can view closings
CREATE POLICY "Staff can view medias cierres"
  ON public.medias_cierres FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'medico', 'enfermera', 'secretaria')
    )
  );

-- Only secretaria and admin can create closings
CREATE POLICY "Secretaria and admin can create medias cierres"
  ON public.medias_cierres FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'secretaria')
    )
  );

-- Only admin can update (reopen) closings
CREATE POLICY "Admin can update medias cierres"
  ON public.medias_cierres FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role = 'admin'
    )
  );

-- NO DELETE policy (closings cannot be deleted)

-- MEDIAS_CIERRE_COUNTER TABLE RLS (admin only)
ALTER TABLE public.medias_cierre_counter ENABLE ROW LEVEL SECURITY;

-- Only admin can view counter
CREATE POLICY "Admin can view medias cierre counter"
  ON public.medias_cierre_counter FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid()
      AND role = 'admin'
    )
  );

-- Allow UPDATE for closing number generation (via function)
CREATE POLICY "Allow medias cierre counter update"
  ON public.medias_cierre_counter FOR UPDATE
  TO authenticated
  WITH CHECK (true);

-- ============================================================================
-- 9. GRANT PERMISSIONS
-- ============================================================================

GRANT SELECT, INSERT ON public.medias_cierres TO authenticated;
GRANT UPDATE (estado, reopened_by, reopen_justificacion, reopened_at, notas, updated_at) ON public.medias_cierres TO authenticated;
GRANT SELECT, UPDATE ON public.medias_cierre_counter TO authenticated;

-- ============================================================================
-- 10. VERIFICATION
-- ============================================================================

DO $$
BEGIN
  -- Check medias_cierres table exists
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'medias_cierres'
  ) THEN
    RAISE EXCEPTION 'medias_cierres table not created';
  END IF;

  -- Check RLS is enabled on medias_cierres
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'medias_cierres' AND rowsecurity = true
  ) THEN
    RAISE EXCEPTION 'RLS not enabled on medias_cierres table';
  END IF;

  -- Check medias_cierre_counter exists
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'medias_cierre_counter'
  ) THEN
    RAISE EXCEPTION 'medias_cierre_counter table not created';
  END IF;

  -- Check RLS is enabled on medias_cierre_counter
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'medias_cierre_counter' AND rowsecurity = true
  ) THEN
    RAISE EXCEPTION 'RLS not enabled on medias_cierre_counter table';
  END IF;

  -- Check medias_cierre_counter has exactly one row
  IF (SELECT COUNT(*) FROM public.medias_cierre_counter) != 1 THEN
    RAISE EXCEPTION 'medias_cierre_counter must have exactly one row';
  END IF;

  -- Verify counter is initialized correctly with CIM prefix
  IF NOT EXISTS (
    SELECT 1 FROM public.medias_cierre_counter
    WHERE id = 1 AND last_number = 0 AND prefix = 'CIM'
  ) THEN
    RAISE EXCEPTION 'medias_cierre_counter not initialized correctly with CIM prefix';
  END IF;

  -- Check zero-tolerance constraint exists
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'medias_diferencia_requires_justificacion'
    AND table_name = 'medias_cierres'
  ) THEN
    RAISE EXCEPTION 'medias_diferencia_requires_justificacion constraint missing (CIE-04)';
  END IF;

  -- Check lockdown trigger exists on medias_sales
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'tr_block_medias_sales_on_closed_day'
  ) THEN
    RAISE EXCEPTION 'tr_block_medias_sales_on_closed_day trigger not created (CIE-05)';
  END IF;

  -- Check immutability trigger exists on medias_cierres
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'tr_medias_cierre_immutability'
  ) THEN
    RAISE EXCEPTION 'tr_medias_cierre_immutability trigger not created';
  END IF;

  RAISE NOTICE 'Medias cierres migration verified successfully';
  RAISE NOTICE 'Counter initialized with CIM prefix (CIE-08)';
  RAISE NOTICE 'Zero-tolerance constraint enabled (CIE-04)';
  RAISE NOTICE 'Sales lockdown trigger on medias_sales (CIE-05)';
END;
$$;

-- ============================================================================
-- Summary of CIE requirements addressed:
-- CIE-01: fecha_cierre UNIQUE (one closing per day)
-- CIE-02: total_efectivo, total_tarjeta, total_transferencia, total_nequi
-- CIE-03: conteo_fisico_efectivo, diferencia calculated
-- CIE-04: medias_diferencia_requires_justificacion (ZERO TOLERANCE)
-- CIE-05: tr_block_medias_sales_on_closed_day (sales lockdown)
-- CIE-06: cierre_photo_path NOT NULL
-- CIE-07: reopened_by, reopened_at, reopen_justificacion (admin reopen)
-- CIE-08: CIM prefix, blocks medias_sales (independent from clinic)
-- ============================================================================
