-- Migration: 027_alerts_table.sql
-- Purpose: Create alerts table for anomaly tracking (payment anulaciones, cierre diferencias)
-- Phase: 08-reports-alerts, Plan: 01
-- Created: 2026-01-26
-- NOTE: Alerts are auto-generated by triggers, resolved manually by admin/medico

-- ============================================
-- 1. ENUM TYPES FOR ALERTS
-- ============================================

-- Types of alerts the system can generate
CREATE TYPE public.alert_tipo AS ENUM (
  'pago_anulado',      -- Payment was annulled
  'diferencia_cierre'  -- Cash closing has difference (faltante or sobrante)
);

COMMENT ON TYPE public.alert_tipo IS 'Tipos de alerta: pago_anulado (pago anulado), diferencia_cierre (diferencia en cierre de caja)';

-- Severity levels for alerts
CREATE TYPE public.alert_severidad AS ENUM (
  'info',        -- Informational only
  'advertencia', -- Warning - needs attention
  'critico'      -- Critical - requires immediate action
);

COMMENT ON TYPE public.alert_severidad IS 'Severidad de alerta: info, advertencia, critico';

-- ============================================
-- 2. ALERTS TABLE
-- ============================================

CREATE TABLE public.alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Alert classification
  tipo public.alert_tipo NOT NULL,
  severidad public.alert_severidad NOT NULL,

  -- Alert content
  titulo VARCHAR(100) NOT NULL,
  descripcion TEXT NOT NULL,

  -- Reference to source record
  referencia_tipo VARCHAR(50),  -- 'payment', 'cash_closing'
  referencia_id UUID,           -- ID of the related record

  -- Resolution tracking
  resuelta BOOLEAN NOT NULL DEFAULT false,
  resuelta_por UUID REFERENCES auth.users(id),
  resuelta_at TIMESTAMPTZ,
  resuelta_notas TEXT,

  -- Audit timestamp
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- ============================================
  -- CONSTRAINTS
  -- ============================================

  -- Resolution must be complete (all fields or none)
  CONSTRAINT alert_resolution_complete CHECK (
    (NOT resuelta AND resuelta_por IS NULL AND resuelta_at IS NULL) OR
    (resuelta AND resuelta_por IS NOT NULL AND resuelta_at IS NOT NULL)
  )
);

-- Table comments
COMMENT ON TABLE public.alerts IS 'Alertas del sistema generadas automaticamente para anomalias (anulaciones, diferencias)';
COMMENT ON COLUMN public.alerts.tipo IS 'Tipo de alerta';
COMMENT ON COLUMN public.alerts.severidad IS 'Nivel de severidad';
COMMENT ON COLUMN public.alerts.titulo IS 'Titulo corto de la alerta';
COMMENT ON COLUMN public.alerts.descripcion IS 'Descripcion detallada de la anomalia';
COMMENT ON COLUMN public.alerts.referencia_tipo IS 'Tipo de registro relacionado (payment, cash_closing)';
COMMENT ON COLUMN public.alerts.referencia_id IS 'ID del registro relacionado';
COMMENT ON COLUMN public.alerts.resuelta IS 'Si la alerta fue revisada/resuelta';
COMMENT ON COLUMN public.alerts.resuelta_por IS 'Usuario que resolvio la alerta';
COMMENT ON COLUMN public.alerts.resuelta_at IS 'Fecha/hora de resolucion';
COMMENT ON COLUMN public.alerts.resuelta_notas IS 'Notas opcionales del usuario al resolver';

-- ============================================
-- 3. INDEXES
-- ============================================

-- Query by creation time (most recent first)
CREATE INDEX idx_alerts_created_at ON public.alerts(created_at DESC);

-- Query by reference (find alerts for specific payment/closing)
CREATE INDEX idx_alerts_referencia ON public.alerts(referencia_tipo, referencia_id);

-- Query unresolved alerts (most common query pattern)
CREATE INDEX idx_alerts_unread ON public.alerts(resuelta, created_at DESC);

-- ============================================
-- 4. ROW LEVEL SECURITY
-- ============================================

ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

-- SELECT: Only admin and medico can view alerts
CREATE POLICY "Admin and medico can view alerts"
  ON public.alerts FOR SELECT
  TO authenticated
  USING (
    public.get_user_role() IN ('admin', 'medico')
  );

-- UPDATE: Only admin and medico can resolve alerts
CREATE POLICY "Admin and medico can resolve alerts"
  ON public.alerts FOR UPDATE
  TO authenticated
  USING (
    public.get_user_role() IN ('admin', 'medico')
  )
  WITH CHECK (
    public.get_user_role() IN ('admin', 'medico')
  );

-- INSERT: No direct inserts allowed (triggers handle this via SECURITY DEFINER)
-- The trigger functions use SECURITY DEFINER and bypass RLS

-- NO DELETE: Alerts are never deleted (audit trail)

-- ============================================
-- 5. GRANT PERMISSIONS
-- ============================================

-- Allow SELECT and UPDATE for authenticated users (RLS handles role filtering)
GRANT SELECT ON public.alerts TO authenticated;
GRANT UPDATE (resuelta, resuelta_por, resuelta_at, resuelta_notas) ON public.alerts TO authenticated;

-- ============================================
-- 6. VERIFICATION
-- ============================================

DO $$
BEGIN
  -- Check alerts table exists
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'alerts'
  ) THEN
    RAISE EXCEPTION 'alerts table not created';
  END IF;

  -- Check RLS is enabled
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'alerts' AND rowsecurity = true
  ) THEN
    RAISE EXCEPTION 'RLS not enabled on alerts table';
  END IF;

  -- Check ENUMs exist
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'alert_tipo'
  ) THEN
    RAISE EXCEPTION 'alert_tipo ENUM not created';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'alert_severidad'
  ) THEN
    RAISE EXCEPTION 'alert_severidad ENUM not created';
  END IF;

  -- Check indexes exist
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE indexname = 'idx_alerts_created_at'
  ) THEN
    RAISE EXCEPTION 'idx_alerts_created_at index not created';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE indexname = 'idx_alerts_referencia'
  ) THEN
    RAISE EXCEPTION 'idx_alerts_referencia index not created';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE indexname = 'idx_alerts_unread'
  ) THEN
    RAISE EXCEPTION 'idx_alerts_unread index not created';
  END IF;

  RAISE NOTICE 'Alerts table migration verified successfully';
END;
$$;
